# Importing libraries

In [4]:
import numpy as np
import tensorflow.keras as keras

# Defining the Input

In [2]:
X = np.array([[1,2],
              [3,4]], dtype= np.uint8)
X = X.reshape((1,2,2,1))

## Configuring the layers

In [5]:
model = keras.models.Sequential()
model.add(keras.layers.UpSampling2D(input_shape= (2,2,1)))
model.summary()

c:\Users\hwenjun\.conda\envs\gans\Lib\site-packages\keras\src\layers\reshaping\up_sampling2d.py:72: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ up_sampling2d (UpSampling2D)    │ (None, 4, 4, 1)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Predicting the output

In [6]:
yhat = model.predict(X)
yhat = yhat.reshape((4,4))
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [3., 3., 4., 4.],
       [3., 3., 4., 4.]], dtype=float32)

# Using different model

In [7]:
model2 = keras.models.Sequential()
model2.add(keras.layers.UpSampling2D(input_shape= (2,2,1), size= (3,3)))
model2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ up_sampling2d_1 (UpSampling2D)  │ (None, 6, 6, 1)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Predicting the output

In [8]:
yhat = model2.predict(X)
yhat = yhat.reshape((6,6))
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [3., 3., 3., 4., 4., 4.],
       [3., 3., 3., 4., 4., 4.],
       [3., 3., 3., 4., 4., 4.]], dtype=float32)

# Different Model

In [9]:
visible = keras.layers.Input(shape= (2,2,1))
outputs = keras.layers.UpSampling2D(input_shape= (2,2,1),
                                   size= (4,4),
                                   interpolation= 'bilinear')(visible)
model3 = keras.models.Model(inputs= visible, outputs= outputs)
model3.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 2, 2, 1)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling2d_2 (UpSampling2D)  │ (None, 8, 8, 1)        │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Predicting the model

In [10]:
yhat = model3.predict(X)
yhat = yhat.reshape((8,8))
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[1.   , 1.   , 1.125, 1.375, 1.625, 1.875, 2.   , 2.   ],
       [1.   , 1.   , 1.125, 1.375, 1.625, 1.875, 2.   , 2.   ],
       [1.25 , 1.25 , 1.375, 1.625, 1.875, 2.125, 2.25 , 2.25 ],
       [1.75 , 1.75 , 1.875, 2.125, 2.375, 2.625, 2.75 , 2.75 ],
       [2.25 , 2.25 , 2.375, 2.625, 2.875, 3.125, 3.25 , 3.25 ],
       [2.75 , 2.75 , 2.875, 3.125, 3.375, 3.625, 3.75 , 3.75 ],
       [3.   , 3.   , 3.125, 3.375, 3.625, 3.875, 4.   , 4.   ],
       [3.   , 3.   , 3.125, 3.375, 3.625, 3.875, 4.   , 4.   ]],
      dtype=float32)

# Useful Links

### [Official Doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling2D)