# Importing libraries

In [1]:
import tensorflow.keras as keras
import numpy as np

## Defining the contrived example

In [2]:
X = np.array([[1,2],[3,4]])
X = X.reshape((1,2,2,1))
X

array([[[[1],
         [2]],

        [[3],
         [4]]]])

## Defining the model

In [3]:
visible = keras.layers.Input(shape= (2,2,1))
hidden1 = keras.layers.Conv2DTranspose(filters= 1,
                                       kernel_size= (1,1),
                                       strides= (2,2))(visible)

model = keras.models.Model(inputs= visible, outputs= hidden1)
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 2, 2, 1)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_transpose                │ (None, 4, 4, 1)        │             2 │
│ (Conv2DTranspose)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

## Setting the model weights

In [4]:
weights = [np.array([[[[1]]]]), np.array([0])]
model.set_weights(weights= weights)

### Predicting the output

In [6]:
yhat = model.predict(X)
yhat = yhat.reshape((4,4))
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[1., 0., 2., 0.],
       [0., 0., 0., 0.],
       [3., 0., 4., 0.],
       [0., 0., 0., 0.]], dtype=float32)

## Defining another model

In [9]:
hidden1 = keras.layers.Conv2DTranspose(filters= 1,
                                       kernel_size= (1,1),
                                       strides= (3,3))(visible)

model02 = keras.models.Model(inputs= visible,
                             outputs= hidden1,
                             name= '3x3_Upsampling_model')
model02.summary()

Model: "3x3_Upsampling_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 2, 2, 1)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_transpose_2              │ (None, 6, 6, 1)        │             2 │
│ (Conv2DTranspose)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

### Predicting the output

In [10]:
weights = [np.array([[[[1]]]]), np.array([0])]
model02.set_weights(weights= weights)

yhat = model02.predict(X)
yhat = yhat.reshape((6,6))
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[1., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)